#!/bin/sh

Fatal() {
    echo  $*
    exit 1
}

Usage() {
    Fatal Usage: setdinardtemp '<temp>'
}

datadir=/home/dockes/projets/rpi-control/thermostat/thermdata/

if test $# != 1 ; then
   Usage
fi
temp=$1

cd $datadir || exit 1
git pull || exit 1
echo $temp > consigne
git add consigne
git commit -m "setconsigne $temp" consigne
git push
